### ISSUE TITLE
Invalid context in iOS

### ISSUE THREAD

**Issue by DonC83** [shaqian/flutter_tflite#130]
When taking an image using the camera and then calling Tflite.runModelOnImage(...) on iOS I keep getting an error with CFRelease(image); 

<img width="1283" alt="Screen Shot 2020-06-22 at 2 47 50 pm" src="https://user-images.githubusercontent.com/594160/85249536-5d80b980-b497-11ea-872f-b731bd88d964.png">

**Comment by shaqian** [comment]
Hi @DonC83 

I think the error is because both width and height are 0. The width and height are from the input image. See [here](https://github.com/shaqian/flutter_tflite/blob/master/ios/Classes/ios_image_load.mm#L50-L51).
You may want to check if the input image is valid. Also check if the app has enough permissions.

Thanks,
Qian

**Comment by DonC83** [comment]
Hi @shaqian,

Thanks, you're right the width and height are 0, not sure how that can be rectified because the image is being passed in after being taken with the camera, so the image exists so need to check why the dimensions are 0. Well it's not an issue with this library so thanks.

Don

**Comment by anonfantom** [comment]
how did it solved im facing same problem 
here is my code 
    var output = await Tflite.runModelOnImage(
      path: image,
      numResults: 5,
      threshold: 0.5,
      imageMean: 127.5,
      imageStd: 127.5,
    );

![Screen Shot 2021-08-14 at 3 43 26 PM](https://user-images.githubusercontent.com/12140858/129446699-d2a5c491-4380-496e-a263-18f4549e1f2c.png)
