### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by Sail338** [shaqian/flutter_tflite#39]
Hi I used your example from the repo for your pose detections, however the output scores are sometimes really low (using the same params as you 0.7 threshold and same code)

**Comment by shaqian** [comment]
Hi, 

The `threshold` parameter is used with keypoint's score. Any keypoint with score lower than the threshold is ignored. 
https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L1326

The pose score is the average score of all keypoints, so it will be smaller than the threshold you specified. You can check if the score of any keypoint is small. Sometimes it's because the image doesn't contain those keypoints. 
https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L1302

Thanks,
Qian
