### ISSUE TITLE
IOS: pod install failed with `use_frameworks!` in podfile

### ISSUE THREAD

**Issue by sosospicy** [shaqian/flutter_tflite#7]
Everything works great on Android.

On IOS, error came out after `pod install`:  
`The 'Pods-Runner' target has transitive dependencies that include static binaries: (test_app/ios/Pods/TensorFlowLite/Frameworks/tensorflow_lite.framework)`

In Podfile:
`
   target 'Runner' do
       use_frameworks!  <-- to use swift plugin
`

**Comment by shaqian** [comment]
Hi sosospicy,

I see you raised another issue related to this. Have you tested the solution suggested by Sh1d0w?
https://github.com/Sh1d0w/multi_image_picker/issues/30

Thanks,
Qian

**Comment by Sh1d0w** [comment]
Hi @shaqian . I've tried to add modular headers as suggested http://blog.cocoapods.org/CocoaPods-1.5.0/ but it seems the Swift plugin does not work without `use_frameworks!` in place, even with modular headers.

I guess you have more iOS experience than me, so any suggestions are welcome. I don't know in which plugin the problem is, all I know is that when you create a new project with `flutter create -i swift` it automatically adds `use_frameworks!`, and your plugin does not seem to work with that enabled.

**Comment by shaqian** [comment]
> Hi @shaqian . I've tried to add modular headers as suggested http://blog.cocoapods.org/CocoaPods-1.5.0/ but it seems the Swift plugin does not work without `use_frameworks!` in place, even with modular headers. So I had to revert that.
> 
> I guess you have more iOS experience than me, so any suggestions are welcome. I don't know in which plugin the problem is, all I know is that when you create a new project with `flutter create -i swift` it automatically adds `use_frameworks!`, and your plugin does not seem to work with that enabled.

Hi Sh1d0w,

Thank you for the information. My plugin hasn't been tested with projects created with -i swift flag. I will give that a look.

Regards,
Qian

**Comment by sosospicy** [comment]
Thank both of you for working so late for this issue.
I tried version 0.0.4, still build error:
After `flutter clean`, `rm -rf ios/Pods`, `rm  ios/Podfile`, and then `flutter run`, got this:
`7 warnings generated.
    <unknown>:0: error: merge-module command failed with exit code 1 (use -v to see invocation)
    Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
    <unknown>:0: error: underlying Objective-C module 'BSImagePicker' not found`

Then run `flutter run` again, got this:
`Xcode's output:
↳
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    While building module 'tflite' imported from /test_app/ios/Runner/GeneratedPluginRegistrant.m:8:
    In file included from <module-includes>:1:
    In file included from /test_app/build/ios/Debug-iphoneos/tflite/tflite.framework/Headers/tflite-umbrella.h:13:
    /test_app/build/ios/Debug-iphoneos/tflite/tflite.framework/Headers/ios_image_load.h:1:10: fatal error: 'vector' file not found
    #include <vector>
             ^~~~~~~~
    1 error generated.
    /test_app/ios/Runner/GeneratedPluginRegistrant.m:8:9: fatal error: could not build module 'tflite'
    #import <tflite/TflitePlugin.h>
     ~~~~~~~^
    2 errors generated.`

**Comment by shaqian** [comment]
Thanks for the update.

The second error is because the tflite plugin uses Objective-C++ code. I added the solution in readme:
https://github.com/shaqian/flutter_tflite#ios
If you get error like "'vector' file not found", please open `ios/Runner.xcworkspace` in Xcode, click Runner > Tagets > Runner > Build Settings, search `Compile Sources As`, change the value to `Objective-C++`;

Regards,
Qian

**Comment by sosospicy** [comment]
@shaqian  Now it runs as expected.  Thanks again! 
I'll fork your repo and try to add some new methods like loading model from files etc..

**Comment by Werdert45** [comment]
I could not find the Compile Sources As option in the build settings, is this still relevant?
